src/html.js
Remove favicon from html.js. Fixes #44.
=> Remove favicon.

src/components/Content/index.js, src/components/Imprint/index.jsx, src/data/imprint.js, src/pages/imprint.jsx
Fix #86. 
The imprint page has now all the content from the original version.
=> Fix #86. Add content to the imprint page.

src/components/Imprint/index.tsx, src/data/imprint.tsx
Fix #106. 
Add missing information on the imprint.
=> Fix #106. Add missing information on the imprint.

static/admin/config.yml
=> Make CMS control master branch

static/admin/config.yml
Enables the [editorial workflow](https://www.netlifycms.org/docs/configuration-options/#publish-mode)
=> Enable editorial workflow in CMS UI

src/components/Imprint/index.tsx, src/components/Imprint/stories.tsx
Fix #136. 
The Imprint has now a pure display component for the storybook.
=> Fix #136. Fix the imprint story.

.circleci/config.yml
=> Run the tests in circleci

src/components/Home/Home.module.scss, src/components/Home/index.tsx
Fix #165 .
Solution based on Used this solution: https://css-tricks.com/hash-tag-links-padding/.
=> Fix page navigation.

src/scss/main.scss, src/scss/variables.scss
=> Fix global header styles.

src/components/BlurryBackground/Background.module.scss, src/components/BlurryBackground/index.tsx, src/components/Hero/Hero.module.scss, src/components/Hero/component.tsx
Followup on #129.
Fix #171.
Done in pair coding session with @Levino 
Restructure the hero section component.
=> Followup on #129. Restructure the hero section component.

src/data/imprint/imprint.json, src/scss/main.scss, src/scss/variables.scss
Add some padding to the top of the headlines if they come in a text div.
=> Improve markdown rendering.

.circleci/config.yml, package.json
=> Perform type checking in CI

package.json, src/components/Navbar/index.tsx, src/utils/hooks.tsx, yarn.lock
Fix #214. 
Add localized link for the navbar brand. If a user clicks now on the brand logo in the navbar she is linked back to the correct home depending on here language.
=> Fix #214. Add localized link for the navbar brand.

envHelper.js, gatsby-config.js, package.json, src/cms/cms.ts, static/admin/config.yml, yarn.lock
Fix #191.
Enable cms preview on PR branches
=> Fix #191. Enable cms preview on PR branches

src/cms/cms.ts, src/cms/preview-templates/FooterPreview.tsx, src/components/Footer/component.tsx, src/components/Footer/index.tsx, src/components/Footer/stories.tsx, src/components/Hero/component.tsx, src/components/Hero/index.tsx, src/components/Hero/stories.tsx, src/components/Home/index.tsx, src/components/Link/index.tsx, src/data/footer/footer.json, src/data/footer/index.tsx, src/data/home/home.json, src/data/home/index.tsx, static/admin/config.yml
=> Add missing fields to home content model

src/cms/preview-templates/FAQPreview.tsx, src/cms/preview-templates/FooterPreview.tsx, src/cms/preview-templates/HomePreview.tsx, src/cms/preview-templates/ImprintPreview.tsx, src/data/faqEntry/index.tsx, src/data/footer/index.tsx, src/data/helpers.test.tsx, src/data/helpers.tsx, src/data/home/home.json, src/data/home/index.tsx, src/data/i18n.test.tsx, src/data/i18n.tsx, src/data/imprint/index.tsx, src/data/testCollection/item1.json, src/data/testCollection/item2.json, static/admin/config.yml, yarn.lock
=> Upgrade Home content model

src/cms/preview-templates/FAQPreview.tsx, src/cms/preview-templates/HomePreview.tsx, src/cms/preview-templates/ImprintPreview.tsx, src/components/Head/index.tsx, src/components/Hero/index.tsx, src/components/Home/index.tsx, src/components/Imprint/index.tsx, src/components/Imprint/stories.tsx, src/components/SEO/index.tsx, src/components/layout.tsx, src/data/faqEntry/faq.json, src/data/faqEntry/helper.test.tsx, src/data/faqEntry/index.tsx, src/data/footer/footer.json, src/data/home/home.json, src/data/home/index.tsx, src/data/imprint/imprint.json, src/data/imprint/index.tsx, src/pages/faq.de.tsx, src/pages/faq.en.tsx, src/pages/imprint.de.tsx, src/pages/imprint.en.tsx, src/pages/index.de.tsx, src/pages/index.en.tsx, static/admin/config.yml
Fix #172.
Also Fix #225.
Add meta data to the cms for the individual pages and add it to the pages for SEO
=> Fix #172. Add SEO 

src/components/Navbar/MenuEntries.tsx, src/utils/hooks.tsx
Fix #192. 
Add a language switcher to the navbar. In the case of a missing language the next available one is used.
=> Fix #192. Add a language switcher to the navbar.

gatsby-browser.js, gatsby-config.js, package.json, src/components/Navbar/MenuEntries.tsx, src/utils/hooks.tsx, yarn.lock
Fix #279.
The contact link in the navbar now leads to the corresponding section on the main page.
=> Fix #279. Fix navigation link.

src/cms/preview-templates/FAQPreview.tsx, src/cms/preview-templates/HomePreview.tsx, src/components/Head/index.tsx, src/data/faqEntry/faq.json, src/data/faqEntry/index.tsx, src/data/faqEntry/types.ts, src/data/home/home.json, src/data/home/types.ts, src/data/imprint/imprint.json, src/data/imprint/index.tsx, src/data/imprint/types.ts, src/data/project/index.tsx, src/data/project/types.ts, static/admin/config.yml
Add localized string widget where possible in the content. Also Fix #335
=> Add localized string widget where possible. Also Fix #335

gatsby-node.js, src/components/Contact/index.tsx, src/components/Contact/stories.tsx, src/components/Home/component.tsx, src/components/Lexoffice/index.tsx, src/data/home/home.json, src/data/home/types.ts, src/data/team/index.tsx
Change public and partner api order on lexoffice landingpage
=> Reorder api techs

src/data/powertools/imprint.html, src/data/powertools/privacy-policy.html
=> Remove google analytics opt-out section in privacy policy.

src/components/Elements/components/form.tsx, src/data/powertools/imprint.html, src/data/powertools/privacy-policy.html
Fix #361 (for real this time).
=> Revise legal notes.

src/components/Freshchat/index.tsx, src/components/Powertools/index.tsx, src/pages/powertools.de.tsx, src/typings/globals.d.ts
Part of #364. 
Add freshchat to the powertools landing page.
=> Part of #365. Add freshchat to the powertools landing page.

src/components/Lexoffice/index.tsx, src/components/Lexoffice/partnerApi.md, src/components/Lexoffice/publicApi.md, src/components/Powertools/description.md, static/_redirects
Fix #350 
Fix #368 
**also**
Fix lexoffice brand name.
=> Fix redirects and lexoffice brand name.

src/components/Powertools/index.tsx, static/_redirects
=> Add powertools pricing.

src/components/Navbar/MenuEntries.tsx, src/components/Navbar/component.tsx, src/components/Navbar/stories.tsx, src/components/TitleBanner/stories.tsx, src/data/navbar/navbar.json, src/data/navbar/types.ts, static/admin/config.yml
Requested during review of #374 
Based on https://github.com/hardforkio/homepage/pull/375/commits/22d0cb23fad50b638ce9c95743d7ac851796a807, and hence subsumes PR #374 (becomes a normal PR once #374 is merged)
=> Add 'Services' link to top navbar

gatsby-browser.js, src/pages/404.tsx
Cleanup after attempt to reproduce #378
=> Add some logging to debug #378 which only happens in deployment.

src/components/Contact/ContactForm.tsx
Remove resetting form in ContactForm component after successful submit.
Fix #389
=> Leave the contact form filled after submission.

CI-improvements-documentation.md, doc/CI-improvements-documentation.md
Collected assumptions about customer journey, Fix #391 
Talked with Levin to evaluate these assumptions, Fix #392
=> Customer journey assumptions

README.md
Add section about user journey focused purpose of the landing page to help focus the work on the project.
Also clean up Readme.
=> Update readme with purpose of landing page
